spring:
  application:
    name: db-service
  config:
    enabled: true
    import: "optional:configserver:http://localhost:8305"


server:
 port: 8300
 

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8301/eureka
#  instance:
#    hostname: localhost
    
    
    



