spring:
  application:
    name: db-service
    
server:
 port: 8300
 

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8301/eureka
  instance:
    hostname: localhost
    
    
    



